### ISSUE TITLE
iff2gif dropping last two frames of animations during conversion

### ISSUE THREAD

**Issue by DownshiftDX** [rheit/iff2gif#3]
I recently discovered iff2gif and have put it to use on Linux Mint 20.3 for converting my anims for opening in ASEprite. I have noticed that all the converted files from saved from PPaint are missing the last two frames of animation, but have the correct frame timing. (8 frame looping anim results in a .gif of frames 1 - 6.) Opening the anim files with Dpaint and re-saving them results in an animation that converts all frames correctly but loses frame timing as Dpaint doesn't support this feature.

There appears to be a difference in how PPaint formats anim files versus Dpaint that doesn't prevent either from loading the files but doesn't convert correctly with iff2gif if the file was saved with PPaint.

**Comment by rheit** [comment]
DPaint ends the animation with the same frames it starts with so it can loop them without any extra work. If you could provide a sample from PPaint, I should be able to do automatic detection. Otherwise, a command line switch is also possible.

**Comment by DownshiftDX** [comment]
I've created two versions of the same animation with one from PPaint and one from Dpaint 4 AGA. (Interestingly, the original non AGA Dpaint 4 cannot load the animations from PPaint and complains about a lack of chip mem.) 

I double checked before uploading and the PPaint version only has 6 frames exported by iff2gif where the other exports all 8.
 
[CS_anim_tests.tar.gz](https://github.com/rheit/iff2gif/files/8436486/CS_anim_tests.tar.gz)

Automatic detection would be fantastic but I am just happy to get any fix. I appreciate the work involved looking at this.

**Comment by rheit** [comment]
Sorry it took a while. This should do the trick. Let me know if it doesn't.
